// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZWLCQ6wtD5Qo0yMo1ngQ8tEeAYpgdt00',
    appId: '1:345535315004:web:8f16a5444d0d5f28819739',
    messagingSenderId: '345535315004',
    projectId: 'flutter-chatapp-firebase',
    authDomain: 'flutter-chatapp-firebase.firebaseapp.com',
    storageBucket: 'flutter-chatapp-firebase.appspot.com',
    measurementId: 'G-ZRQ4PXXQQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpyWWABWNthT4IgiPWNK8wyT3GAOWPGdA',
    appId: '1:345535315004:android:bd0748e3d7da415c819739',
    messagingSenderId: '345535315004',
    projectId: 'flutter-chatapp-firebase',
    storageBucket: 'flutter-chatapp-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7keCmxQUfpc3AQPyd8OTNEa8ptu3sr_I',
    appId: '1:345535315004:ios:56cab49ea502ddc3819739',
    messagingSenderId: '345535315004',
    projectId: 'flutter-chatapp-firebase',
    storageBucket: 'flutter-chatapp-firebase.appspot.com',
    iosClientId: '345535315004-d65f8adl53tue45ai10hbh2sdehelctd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7keCmxQUfpc3AQPyd8OTNEa8ptu3sr_I',
    appId: '1:345535315004:ios:56cab49ea502ddc3819739',
    messagingSenderId: '345535315004',
    projectId: 'flutter-chatapp-firebase',
    storageBucket: 'flutter-chatapp-firebase.appspot.com',
    iosClientId: '345535315004-d65f8adl53tue45ai10hbh2sdehelctd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatappFirebase',
  );
}
