# Uncomment the next line to define a global platform for your project
platform :ios, '10.11'
inhibit_all_warnings!

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # Pods for Runner
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
    # flutter_additional_ios_build_settings(target)
    
    # # ADD THE NEXT SECTION
    # target.build_configurations.each do |config|
    #   config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
    #     '$(inherited)',
    #     'AUDIO_SESSION_MICROPHONE=0'
    #   ]
    # end
  end
end